site_name: F5 Advanced WAF
theme:
    name: readthedocs
markdown_extensions:
  - admonition
docs_dir: source
site_dir: build
nav:
    - Giới thiệu tổng quan: index.md
    - Chuẩn bị môi trường: pre.md
    - Tạo các chính sách bảo mật: securitypolicy.md
    - Các thiết lập và tinh chỉnh khác: other.md
    - Bỏ qua chế độ chặn lọc WAF: bypass.md
